# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      jasypt.encryptor.password: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
      jwt.key: ${{ secrets.JWT_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set Environment Variables
      run: |
        echo "Setting Jasypt Password as an environment variable"
        echo "jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}" >> $GITHUB_ENV
        echo "Setting JWT Key as an environment variable"
        echo "jwt.key=${JWT_KEY}" >> $GITHUB_ENV
    - name: Build with Maven
      run: mvn -B package --file pom.xml
